# Generated by Django 3.0.1 on 2019-12-18 18:20

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModeloImpressora',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Grupo')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Permissao')),
            ],
        ),
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('nome', models.CharField(max_length=50)),
                ('cont_impressoes', models.IntegerField()),
                ('cont_max_impressoes', models.IntegerField(default=1000)),
                ('numero_serie', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('online', models.BooleanField(default=False)),
                ('operante', models.BooleanField(default=False)),
                ('necessita_reparo', models.BooleanField(default=False)),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Local')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ModeloImpressora')),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
