# Generated by Django 3.0 on 2019-12-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cont_impressoes', models.IntegerField()),
                ('numero_serie', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=50)),
                ('online', models.BooleanField()),
            ],
        ),
    ]
