# Generated by Django 3.0 on 2019-12-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='numero_serie',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
