# Generated by Django 3.0 on 2019-12-17 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191217_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloImpressora',
            fields=[
                ('nome', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ModeloImpressora'),
        ),
    ]
