# Generated by Django 3.0.1 on 2019-12-18 13:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20191217_1916'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='impressora',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modeloimpressora',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
