# Generated by Django 3.0.1 on 2019-12-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20191218_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressora',
            name='cont_max_impressoes',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='impressora',
            name='necessita_reparo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impressora',
            name='operante',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
